### ISSUE TITLE
Add more information to the name of the video taken

### ISSUE THREAD

**Issue by amustea** [groupon/Selenium-Grid-Extras#183] opened 2015-12-04 19:59 UTC
as of now name is just a Guid.
It would be nice to have more information there (like the test class/group/run name). This way it would be much easier to detect which video shows which run.

**Comment by plessbd** [comment] 2015-12-10 13:19
seems like a duplicate/variation of #97

**Comment by smccarthy** [comment] 2016-01-24 22:27
Closing as this seems like a duplicate of #97 . @amustea If you think it is not a duplicate, please leave a comment here and I can reopen.

Thank you.

**Closed by smccarthy** 2016-01-24 22:27 UTC
