### ISSUE TITLE
Video is not recording if width or heigth of screen is odd number

### ISSUE THREAD

**Issue by Hellmin** [groupon/Selenium-Grid-Extras#192] opened 2016-01-19 08:25 UTC
Preconditions:
- Screen resolution: 1023x768
- Video recording is Enabled

Scenario:
- Try to launch any test

Actual result:
- Exception: `[pool-2-thread-2] ERROR org.ffmpeg - [libx264 @ 0000000020389AE0] width not divi
  sible by 2 (1023x768)
  [pool-2-thread-2] WARN com.xuggle.xuggler - Error: could not open codec (../../.
  ./../../../../csrc/com/xuggle/xuggler/StreamCoder.cpp:831)
  [pool-2-thread-2] WARN com.xuggle.xuggler - writeTrailer() with no matching call
  to writeHeader() (../../../../../../../csrc/com/xuggle/xuggler/Container.cpp:86
  3)`
- Video has not been recorded

Desired result:
- Video is cropped by single pixel by height or width, or both of them
- Video has been successfully recorded

**Comment by Hellmin** [comment] 2016-01-19 08:32
![screenshot](https://cloud.githubusercontent.com/assets/10207747/12413495/519ee9ee-bea0-11e5-9e9f-d09506fcdb00.png)

**Comment by smccarthy** [comment] 2016-04-29 17:13
@Hellmin I think this is a known issue, that you need even numbers. @dimacus mentioned this somewhere I think.

**Comment by smccarthy** [comment] 2016-12-07 16:19
Closing this, as its a duplicate of https://github.com/groupon/Selenium-Grid-Extras/issues/276 (which has more info in it)

**Closed by smccarthy** 2016-12-07 16:19 UTC
