### ISSUE TITLE
Multiple instance videos stomping on each other

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#102] opened 2015-03-19 22:44 UTC
I kicked off a few tests in parallel and a few hit the same VM on a separate browser session. 
Toward's the end of the Video I noticed another SESSION opened a browser, maximized and covered the first session's browser...

**Comment by shankarkc** [comment] 2016-08-08 04:43
I guess video is recorded at OS level and not at browser  session level. So you are seeing this...can you use multiple nodes. But image capture works at browser level. So with current grid implementation i think you can either
1. use multiple nodes and run only one test on one node to capture video if video is must for you
2. use single node run multiple bowers on same node ...but rely on screenshots to find out what went wrong.

**Comment by smccarthy** [comment] 2016-10-14 19:09
@shankarkc is correct. There was an idea to stitch together screenshots, to make videos of the browser, but currently it is just an idea :
https://github.com/groupon/Selenium-Grid-Extras/pull/229

**Comment by smccarthy** [comment] 2016-12-07 02:00
Closing this, since it is not a bug.

**Closed by smccarthy** 2016-12-07 02:00 UTC
