### ISSUE TITLE
Hub role, Driver update question (failure after selecting 1)

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#134] opened 2015-06-30 18:25 UTC
Any clue why the Hub role asks for:

Would you like WebDriver, IEDriver and ChromeDriver to auto update (1-yes/0-no)
Default Value: 1

This is where it fails for me on setup with the latest release (Java 1.7 update 79)

Would you like WebDriver, IEDriver and ChromeDriver to auto update (1-yes/0-no)
Default Value: 1

'1' was set as your value
org.dom4j.DocumentException: sun.security.validator.ValidatorException: PKIX pat
h building failed: sun.security.provider.certpath.SunCertPathBuilderException: u
nable to find valid certification path to requested target Nested exception: sun
.security.validator.ValidatorException: PKIX path building failed: sun.security.
provider.certpath.SunCertPathBuilderException: unable to find valid certificatio
n path to requested target
        at org.dom4j.io.SAXReader.read(SAXReader.java:484)
        at org.dom4j.io.SAXReader.read(SAXReader.java:291)
        at com.groupon.seleniumgridextras.downloader.webdriverreleasemanager.Web
DriverReleaseManager.<init>(WebDriverReleaseManager.java:52)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.loadWebDriverRele
aseManager(RuntimeConfig.java:85)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.getReleaseManager
(RuntimeConfig.java:73)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.setDriverAut
oUpdater(FirstTimeRunConfig.java:261)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.customiseCon
fig(FirstTimeRunConfig.java:99)
        at com.groupon.seleniumgridextras.config.Config.initilizedFromUserInput(
Config.java:233)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfi
g.java:133)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridEx
tras.java:72)
Nested exception:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExce
ption: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unkn
own Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrent
Entity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineD
ocVersion(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown So
urce)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Un
known Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(Unknown Source)
        at org.dom4j.io.SAXReader.read(SAXReader.java:465)
        at org.dom4j.io.SAXReader.read(SAXReader.java:291)
        at com.groupon.seleniumgridextras.downloader.webdriverreleasemanager.Web
DriverReleaseManager.<init>(WebDriverReleaseManager.java:52)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.loadWebDriverRele
aseManager(RuntimeConfig.java:85)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.getReleaseManager
(RuntimeConfig.java:73)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.setDriverAut
oUpdater(FirstTimeRunConfig.java:261)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.customiseCon
fig(FirstTimeRunConfig.java:99)
        at com.groupon.seleniumgridextras.config.Config.initilizedFromUserInput(
Config.java:233)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfi
g.java:133)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridEx
tras.java:72)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed:
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find vali
d certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Sour
ce)
        ... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to
 find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown
 Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 35 more
Nested exception: javax.net.ssl.SSLHandshakeException: sun.security.validator.Va
lidatorException: PKIX path building failed: sun.security.provider.certpath.SunC
ertPathBuilderException: unable to find valid certification path to requested ta
rget
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source
)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unkn
own Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrent
Entity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineD
ocVersion(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown So
urce)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Un
known Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(Unknown Source)
        at org.dom4j.io.SAXReader.read(SAXReader.java:465)
        at org.dom4j.io.SAXReader.read(SAXReader.java:291)
        at com.groupon.seleniumgridextras.downloader.webdriverreleasemanager.Web
DriverReleaseManager.<init>(WebDriverReleaseManager.java:52)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.loadWebDriverRele
aseManager(RuntimeConfig.java:85)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.getReleaseManager
(RuntimeConfig.java:73)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.setDriverAut
oUpdater(FirstTimeRunConfig.java:261)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.customiseCon
fig(FirstTimeRunConfig.java:99)
        at com.groupon.seleniumgridextras.config.Config.initilizedFromUserInput(
Config.java:233)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfi
g.java:133)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridEx
tras.java:72)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed:
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find vali
d certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Sour
ce)
        ... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to
 find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown
 Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 35 more
Exception in thread "main" java.lang.NullPointerException
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.setDriverAut
oUpdater(FirstTimeRunConfig.java:262)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.customiseCon
fig(FirstTimeRunConfig.java:99)
        at com.groupon.seleniumgridextras.config.Config.initilizedFromUserInput(
Config.java:233)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfi
g.java:133)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridEx
tras.java:72)

C:\ROOT\Selenium_Jars>

**Comment by smccarthy** [comment] 2015-06-30 18:26
Isn't this the same as : https://github.com/groupon/Selenium-Grid-Extras/issues/130
?

**Comment by cktech529** [comment] 2015-07-01 16:51
The same error, but a question about why in the role of Hub does the hub require the webdrivers (just curious if it's by design)

**Comment by smccarthy** [comment] 2015-07-09 01:58
I believe it just asks because the hub may want to auto update the WebDriver jar file (it probably doesn't care about the IEDriverServer or chromedriver, but I think right now its just 1 option for all 3.

**Comment by smccarthy** [comment] 2015-07-14 22:55
Closing this as the question was answered (it is by design and would require some some tweaking to make work differently for hub and nodes). and there is another issue for the error "unable to find valid certification path to requested target"

**Closed by smccarthy** 2015-07-14 22:55 UTC
