### ISSUE TITLE
Gecko driver won't update

### ISSUE THREAD

**Issue by mstankovic86** [groupon/Selenium-Grid-Extras#278] opened 2016-11-25 13:40 UTC
steps for reproduction:
1. configure node to use gecko driver 0.9
2. start extras - gecko is 0.9
3. update config to use gecko 0.11.1
4. restart node

-> gecko is still 0.9

NOTE: if you manually do host_:3000/download_geckodriver you'll get response:
`
{
  "exit_code": 0,
  "out": [
    "File already downloaded, will not download again"
  ],
  "error": [],
  "file_full_path": [
    "C:\\tmp\\webdriver\\geckodriver\\geckodriver_0.11.1.zip"
  ],
  "file": [
    "geckodriver_0.11.1.zip"
  ]
}`

WORKAROUND: go to tmp/webdriver/geckodriver,  manually remove old driver, run again end_point (or restart node) and new gecko will be downloaded

![screen shot 2016-11-25 at 2 31 30 pm](https://cloud.githubusercontent.com/assets/8803779/20626931/210e165c-b31d-11e6-8b03-d00d66925c80.png)

**Comment by smccarthy** [comment] 2016-11-25 18:03
I know about this issue, but I was hoping people wouldn't run into it. The file name format changed a few times with geckodriver, but i think it's stable now. We can probably put some logic in around older versions, but it's probably not a high priority (especially with a work around ).

**Comment by mstankovic86** [comment] 2016-11-25 19:51
Yes there is workaround but im not really happy if i must go into 100+ vms
and do some deleting manually

**Comment by smccarthy** [comment] 2016-11-25 20:06
Makes sense.  I can work on a code fix soon. I'll be busy until Tuesday, but I think I can def find time on Wednesday. I can also merge PRs if someone else has a fix .

**Comment by smccarthy** [comment] 2016-11-30 00:42
I also noticed the latest version of geckodriver when I run FirstTimeRunConfig on a windows computer, is showing as 0.10.0. This is not right, since it should be 0.11.1 . I started to look at this issue.

**Comment by smccarthy** [comment] 2016-12-04 21:33
I take back my comment about knowing about the issue. It should have worked fine on Windows, since that file name didn't change since 0.9.0. I now think the issue is that the other drivers have the version number in them, but geckodriver is just `geckodriver`. We probably have to make the executable `geckodriver_0.9.0` (and similar for `geckodriver_0.11.1`). PRs welcome, though I will try and figure it out and test it sometime this week.

**Comment by smccarthy** [comment] 2016-12-04 22:27
@mstankovic86 I believe I fixed this with https://github.com/groupon/Selenium-Grid-Extras/commit/e020056e1b6031c8c8e12e51bb2f3323eda13319 . I released a new version, 1.12.9 with this fix. Please let me know if it works. Thank you!

@mstankovic86 ^

**Comment by mstankovic86** [comment] 2016-12-05 08:53
Thanks, I'll let you know later today.

--
*Miloš Stanković*  |  *Team Lead*
Emisia Consulting, Kragujevac, Serbia

**Comment by mstankovic86** [comment] 2016-12-05 16:20
@smccarthy 
it works! Thanks

**Comment by smccarthy** [comment] 2016-12-05 16:49
Awesome, I'm glad it works. Closing.

**Closed by smccarthy** 2016-12-05 16:49 UTC
Labels: waitingoninfo
