### ISSUE TITLE
cannot build selenium-grid-extra due to error Could not find artifact xuggle:xuggle-xuggler:jar:5.4

### ISSUE THREAD

**Issue by shankarkc** [groupon/Selenium-Grid-Extras#244] opened 2016-07-11 05:10 UTC
Hi it looks like xuggle-xuggler jar is not available anymore. Work on it stopped 4 years back. So we couldnt build it as its not cached in our company local repository. Is there any plan to move to some other framework? If not can you please host  xuggle-xuggler:jar:5.4 somewhere outside so that others can build/use it? As of now I cannot build grid-extras locally due to this dependency.

**Comment by smccarthy** [comment] 2016-07-11 16:52
This is a duplicate of #232 . Closing this one.

We do need to come up with a solution soon. My idea is that we put the xuggle dependencies in this repo and have it as a local dependency. I just don't know if there is any legal concerns with this.

I do think we should use a different video library in the future though. One where it is still actively developed. I do not have the time to research this second part anytime soon.

**Closed** 2016-07-11 16:52 UTC
