### ISSUE TITLE
Video Session  seems to have timed out

### ISSUE THREAD

**Issue by darmalovan** [groupon/Selenium-Grid-Extras#72] opened 2014-11-20 16:46 UTC
I'm trying to capture videos on the vm running the selenium test, but it seems that video is not created.
I can see the file but it is 0 bytes.

The log i'm getting is:

20 Nov 2014 18:42:45 [Thread-5] INFO  tasks.VideoRecorder  - Starting video recording for session: 9a797c2d-ff01-4953-b7ef-690d23eae5a3, on host: 10.149.18.66, done: false, cancelled: false
20 Nov 2014 18:42:45 [pool-2-thread-1] INFO  video.VideoRecorderCallable  - Starting video recording for session 9a797c2d-ff01-4953-b7ef-690d23eae5a3 to C:\RemoteWebDriver\video_output
20 Nov 2014 18:42:48 [Thread-5] INFO  video.VideoRecordingThreadPool  - Video Session 9a797c2d-ff01-4953-b7ef-690d23eae5a3 seems to have timed out, removing it from memory
20 Nov 2014 18:43:34 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - Setting video source directory to C:\RemoteWebDriver\video_output
20 Nov 2014 18:43:34 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4
20 Nov 2014 18:43:34 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4 does exist, responding with 404
20 Nov 2014 18:43:35 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4
20 Nov 2014 18:43:35 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4 does exist, responding with 404
20 Nov 2014 18:43:36 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4
20 Nov 2014 18:43:36 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4 does exist, responding with 404
20 Nov 2014 18:43:38 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4
20 Nov 2014 18:43:38 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4 does exist, responding with 404
20 Nov 2014 18:43:40 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4
20 Nov 2014 18:43:40 [Thread-5] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\RemoteWebDriver\video_output\9a797c2d-ff01-4953-b7ef-690d23eae5a3.mp4 does exist, responding with 404
 

thanks!

**Comment by iconner** [comment] 2015-10-16 15:40
I'm also seeing this issue on Windows 7

**Comment by smccarthy** [comment] 2016-06-26 15:33
I think this is a duplicate of #93 . Closing this one. If you think it is different, please comment back and I can reopen. Thanks.

**Closed by smccarthy** 2016-06-26 15:33 UTC
