### ISSUE TITLE
Browser close immediately after test starts

### ISSUE THREAD

**Issue by Andro72** [groupon/Selenium-Grid-Extras#191] opened 2016-01-15 10:47 UTC
# Description

Immediately after test started browser window is closed. It is same on Chrome and IE. Browser window is visible for +-2 seconds.
Test works on Selenium Grid, and also by using Driver, but not on Selenium Grid Extras.

# Log output

```
11:14:42.581 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Executing: [new session: Capabilities [{EnableNativeEvents=false, browserName=internet explorer, chromeOptions={BrowserCommandLineArguments=, BrowserAttachTimeout=-10675199.02:48:05.4775808, ForceShellWindowsApi=false, UsePerProcessProxy=false, IgnoreZoomLevel=false, ElementScrollBehavior=0, EnablePersistentHover=true, PageLoadStrategy=0, EnableNativeEvents=false, IntroduceInstabilityByIgnoringProtectedModeSettings=false, ValidateCookieDocumentType=true, EnsureCleanSession=false, UnexpectedAlertBehavior=0, ForceCreateProcessApi=false, RequireWindowFocus=false, InitialBrowserUrl=}, version=, platform=WINDOWS}]])
11:14:42.601 INFO [21] org.openqa.selenium.remote.server.DefaultDriverProvider - Creating a new session for Capabilities [{EnableNativeEvents=false, browserName=internet explorer, chromeOptions={BrowserCommandLineArguments=, BrowserAttachTimeout=-10675199.02:48:05.4775808, ForceShellWindowsApi=false, UsePerProcessProxy=false, IgnoreZoomLevel=false, ElementScrollBehavior=0, EnablePersistentHover=true, PageLoadStrategy=0, EnableNativeEvents=false, IntroduceInstabilityByIgnoringProtectedModeSettings=false, ValidateCookieDocumentType=true, EnsureCleanSession=false, UnexpectedAlertBehavior=0, ForceCreateProcessApi=false, RequireWindowFocus=false, InitialBrowserUrl=}, version=, platform=WINDOWS}]
11:14:43.702 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Done: [new session: Capabilities [{EnableNativeEvents=false, browserName=internet explorer, chromeOptions={BrowserCommandLineArguments=, BrowserAttachTimeout=-10675199.02:48:05.4775808, ForceShellWindowsApi=false, UsePerProcessProxy=false, IgnoreZoomLevel=false, ElementScrollBehavior=0, EnablePersistentHover=true, PageLoadStrategy=0, EnableNativeEvents=false, IntroduceInstabilityByIgnoringProtectedModeSettings=false, ValidateCookieDocumentType=true, EnsureCleanSession=false, UnexpectedAlertBehavior=0, ForceCreateProcessApi=false, RequireWindowFocus=false, InitialBrowserUrl=}, version=, platform=WINDOWS}]]
11:14:46.941 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Executing: [delete session: 3676e414-922a-4b39-ae95-cd065234be7a])
11:14:47.801 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Done: [delete session: 3676e414-922a-4b39-ae95-cd065234be7a]
```

**Comment by supernager** [comment] 2016-01-15 12:09
We are also seeing this issue on the Selenium Grid. I currently rather see the error cause with the latest `selenium-server-standalone` version 2.49.0
A downgrade on the Selenium Hub and Node to 2.48.0 fixed this problem, but is of course no solution!

**Comment by Andro72** [comment] 2016-01-15 13:00
@supernager I tried it, and it works for me.. Thanks

**Comment by wpballard** [comment] 2016-01-15 16:38
I am seeing this same error. It is related to the 2.49.0 release on 1-13-16. There are major changes in how the grid is implemented.

**Comment by Chris2m** [comment] 2016-01-15 19:27
Same issue with the update to 2.49.0. I tried increasing the timeouts, but only got the same result.

```webDriver.manage().timeouts().pageLoadTimeout(25, TimeUnit.SECONDS);```

**Comment by smccarthy** [comment] 2016-01-17 17:47
@Chris2m @wpballard @Andro72 @supernager I am on OSX and downloaded SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar and set it up as a hub + node (it downloaded selenium 2.49.0). I ran a chrome test and it passed a few times in a row. Can you point out what version of selenium grid extras you are using? What OS are you all using (I see Andro72 is on Windows, but is anyone seeing this issue on OSX?)?

Is anyone else having this issue when running a single node + hub with the same jar?

I'll try a few more scenarios to see if I can reproduce.

**Comment by Chris2m** [comment] 2016-01-17 20:34
I have the Grid setup with version 2.49.0 on Windows 8 VMs:

1. hub+node
2. nodes

It was working before it got auto-upgraded.

**Comment by smccarthy** [comment] 2016-01-17 20:48
I reproduced this on Windows 7 (1 Windows VM acting as hub and node).

**Comment by smccarthy** [comment] 2016-01-18 04:22
So far I think I narrowed it down to the timeout attribute in the hub json. I updated it to use :
  "timeout": 0,
and it seems to work better. Again, this isn't an optimal solution, but it is some progress. Can anyone else try to see if setting timeout helps them?

**Comment by Chris2m** [comment] 2016-01-18 12:12
Did not work for me - here's my hub json. Anything different on your end? 

```json
{
  "port": 4444,
  "newSessionWaitTimeout": 25000,
  "servlets": [
    "com.groupon.seleniumgridextras.grid.servlets.SeleniumGridExtrasServlet",
    "com.groupon.seleniumgridextras.grid.servlets.ProxyStatusJsonServlet"
  ],
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "browserTimeout": 0,
  "timeout": 0,
  "maxSession": 5
}
```

**Comment by tk8817** [comment] 2016-01-18 15:00
We are having the same issues, we tried altering the timeouts after digging into the logs, but it did not help the issue. We noticed that the tests crash once we hit code where there is a wait over 5 seconds (which is what the polling timeout is set to by default). Upping it seems to not be respected by the app.

**Comment by Andro72** [comment] 2016-01-18 15:25
@tk8817 have you read the post from @supernager ? 
Solution is to downgrade to 2.48.2. Than it is working.

**Comment by tk8817** [comment] 2016-01-18 15:38
@Andro72 Indeed,we downgraded almost immediately after the update came out. Can't call that a solution though :) . Hoping my past will give further insight that it is a cross platform matter and appears to be tied to a polling interval mismatch in 2.49 .

**Comment by Yukonjess101** [comment] 2016-01-18 15:52
Downgrading worked for us...
Server 2012R2 - Hub
Win7 - node
Win8.1 - node
Win10 x2 - nodes

We were seeing the same issues in our CI run.  As soon as the test was loaded, the session failed:
- UnknownError: Session [84194998-45ba-4617-8e10-ef83f4bb5969] was terminated due to TIMEOUT

**Comment by smccarthy** [comment] 2016-01-18 21:31
I opened https://github.com/SeleniumHQ/selenium/issues/1495 on the selenium project since I reproduced the issue without grid extras.

**Comment by tk8817** [comment] 2016-01-19 16:35
thanks @smccarthy , seems this issue exists outside the realm of selenium-grid-extras. The issue is gaining traction on the selenium side.

**Comment by smccarthy** [comment] 2016-01-21 17:44
Can people try this again? 2.49.1 was released

http://selenium-release.storage.googleapis.com/index.html?path=2.49

**Comment by tk8817** [comment] 2016-01-21 20:23
only one commit is showing in 2.49.1 and it appears related to python specifically. I commented on the ticket we opened on the selenium side to see whats up

**Comment by smccarthy** [comment] 2016-01-24 22:21
Closing as this is fixed. @Andro72 If you still see the issue, please leave another comment. Thanks.

**Closed by smccarthy** 2016-01-24 22:21 UTC
