### ISSUE TITLE
Opera Driver supprot

### ISSUE THREAD

**Issue by Shnitzelil** [groupon/Selenium-Grid-Extras#121] opened 2015-05-21 13:45 UTC
Please add opera driver support 
https://github.com/operasoftware/operachromiumdriver/releases

**Comment by smccarthy** [comment] 2016-06-26 14:42
Duplicate of https://github.com/groupon/Selenium-Grid-Extras/issues/196 . Leaving that one open and  closing this one. 

@Shnitzelil Can you answer this question in the other issue ? 
How do you use Opera with selenium? Do you get the driver from https://github.com/operasoftware/operachromiumdriver/releases and use -Dwebdriver.opera.driver=/path/to/opera/driver ? Or is it -Dwebdriver.chrome.driver=/path/to/opera/driver ?

I ask because, if it is webdriver.chrome.driver , how do you use Chrome and Opera on the same node ?

**Closed by smccarthy** 2016-06-26 14:42 UTC
